### ISSUE TITLE
Listen to XDebug: File not found

### ISSUE THREAD

**Issue by vielhuber** [lfurzewaddock/vscode-wsl-workspacefolder#11]
Hello!

I use Xdebug php debugging in vscode and get the following error when "Listen for XDebug" runs and I open a website on my local machine:

![image](https://user-images.githubusercontent.com/3183737/64658147-ac90bd00-d436-11e9-89bb-0c6d17ef6e08.png)

Does your plugin fit for this use case? I somehow need to convert the WSL paths to Windows paths in order to get windows find those paths.

**Comment by lfurzewaddock** [comment]
Sorry for the late reply @vielhuber.

This extension only converts the windows 'workspace' folder path to to the equivalent WSL path.

**Comment by vielhuber** [comment]
Thank you for your answer. May I ask you if you know how to fix the problem mentionned above?

**Comment by lfurzewaddock** [comment]
If you need a windows path use the `${workspaceFolder}` variable: [https://code.visualstudio.com/docs/editor/variables-reference](https://code.visualstudio.com/docs/editor/variables-reference)

Also, perhaps the following link is helpful;
[https://www.cloudways.com/blog/php-debug/#configure-xdebug](https://www.cloudways.com/blog/php-debug/#configure-xdebug)

**Comment by vielhuber** [comment]
Cool, thanks for your help and keep up the good work!
